# dev
global_url = 'https://dev.seltool.gdmseeds.com/global/theme/v1/values'
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios'
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios/{idScenario}/regions'
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios/{idScenario}/materials'
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/scenario-commander/v1/scenarios?type='
scenarios_url = 'http://localhost:8201/selection-tool/scenario-query/v1/scenarios/{idScenario}'
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/scenario-query/v1/regions'
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/model-manager/v1/materials'
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/model-manager/v1/materials?run='
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/scenario-commander/v1/agronomics/sets'
scenarios_url = 'https://dev.seltool.gdmseeds.com/selection-tool/scenario-commander/v1/agronomics/sets/{id_set}/summaries'


# qa
qa_global_url = 'https://qa.seltool.gdmseeds.com/global/theme/v1/values'
qa_regions_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-query/v1/regions'
qa_materials_url = 'https://qa.seltool.gdmseeds.com/selection-tool/model-manager/v1/materials'
qa_materials_run_url = 'https://qa.seltool.gdmseeds.com/selection-tool/model-manager/v1/materials?run='
qa_agronomics_sets_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-commander/v1/agronomics/sets'
qa_set_summaries_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-commander/v1/agronomics/sets/{id_set}/summaries'
qa_theme_path_url = 'https://qa.seltool.gdmseeds.com/selection-tool/theme/v1/'
qa_scenarios_type_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-commander/v1/scenarios?'
qa_scenarios_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios'
qa_scenario_id_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios/{idScenario}'
qa_scenario_id_region_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios/{idScenario}/regions'
qa_scenario_id_materials_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios/{idScenario}/materials'
qa_scenario_id_agronomics_sets_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios/{idScenario}/agronomics/sets?name={name}'
qa_scenario_id_versions_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-query/v1/scenarios/{idScenario}/versions'
qa_scenarios_run_url = 'https://qa.seltool.gdmseeds.com/selection-tool/model-manager/v1/scenarios/run'
qa_graphics_report_url = 'https://qa.seltool.gdmseeds.com/selection-tool/scenario-query/v1/graphics?report='
qa_agronomics_run_id_url = 'https://qa.seltool.gdmseeds.com/selection-tool/model-manager/v1/agronomics?run={runId}'
qa_agronomics_url = 'https://qa.seltool.gdmseeds.com/selection-tool/model-manager/v1/agronomics'
qa_get_products_url = 'https://adb-6411001487030227.7.azuredatabricks.net/api/2.1/jobs/run-now'

